delete from Topics;

insert into Topics (name, description) values 
('None', 'None'),
('Crisis', 'The theme of the financial crisis is more relevant than ever today, when inflation in many, even developed, countries of the world reaches double digits, food prices rise, fuel prices rise, which only further exacerbates the energy crisis around the world.'),
('Crypto', 'Cryptocurrencies, a relatively recent phenomenon, however, have been widely publicized in many media outlets and have a dubious reputation. Nevertheless, the crypto industry market is still growing rapidly and gaining momentum, despite the so-called "crypto winter" that has been going on for almost a year, which only indicates that cryptocurrencies have already become part of the global economy and should be considered by all investors and financial analysts.'),
('Energetics', 'Energy is one of the key sectors of the economy in many countries of the world. Since industrialization, a country''s ability to provide itself with energy resources has been a critical aspect of its successful development. That is why this is one of the most important topics in the financial world, and the issue of energy is especially acute now, during the global energy crisis.'),
('Investements', 'Investments - a long-term investment of capital in some part of the country''s economy - is very risky, on the one hand, an event shrouded in a veil of fear and distrust on the part of a certain part of society, but on the other hand, it is an incredibly necessary and important matter for preserving and increasing human capital and even states.'),
('Taxation', 'The topic of taxation is very important for all participants in the economic cycle. Every legal taxpayer, and even more so an investor, must know how much taxes he pays to the state and what is the structure of these taxes, not only open, but also initially included in the price of the final product.'),
('Fundamental analysis', 'Fundamental analysis is a way to analyze the performance of a business, its sustainability and attractiveness to investors in terms of its fundamental indicators, such as EBITDA, P/E, P/S, ROCE and much more.'),
('Technical analysis', 'Technical analysis is a way of predicting the rate of a currency pair or a stock based on the behavior of the chart of this rate for the previous period of time. Often used by traders to decide whether to buy or sell assets.'),
('Macroeconomics', 'Macroeconomic news may include discussion and analysis of major world events, as well as their impact on the global economy and the economies of individual states.'),
('Microeconomics', 'The microeconomics thread contains references to events that can have a significant impact on small enterprises and businesses, as well as directly affecting small entrepreneurs and, possibly, their clients.')